In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('dataset.csv')

In [3]:
columns = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14']

In [4]:
df[columns].head()

X1        X2        X3   X4        X5        X6        X7        X8  \
0  0.171429  0.030508  0.045455  0.6  0.787026  0.976996  0.788192  0.018349   
1  0.300000  0.033898  0.072727  1.0  0.870257  0.983912  0.777622  0.011468   
2  0.314286  0.332203  0.072727  0.6  0.730722  0.951887  0.424290  0.043578   
3  0.314286  0.332203  0.072727  0.6  0.730722  0.951887  0.424290  0.043578   
4  0.314286  0.155932  0.045455  0.6  0.856793  0.979326  0.753275  0.029817   

         X9       X10       X11       X12       X13     X14  
0  0.956066  0.134645  0.000000  0.775162  0.706827  0.5625  
1  0.955782  0.129048  0.000495  0.777505  0.673568  0.9375  
2  0.957102  0.155044  0.004293  0.779986  0.741602  0.5625  
3  0.957102  0.155044  0.004293  0.779986  0.741602  0.5625  
4  0.956226  0.137795  0.001814  0.776052  0.734925  0.5625

In [5]:
df.head()

X1        X2        X3   X4        X5        X6        X7        X8  \
0  0.171429  0.030508  0.045455  0.6  0.787026  0.976996  0.788192  0.018349   
1  0.300000  0.033898  0.072727  1.0  0.870257  0.983912  0.777622  0.011468   
2  0.314286  0.332203  0.072727  0.6  0.730722  0.951887  0.424290  0.043578   
3  0.314286  0.332203  0.072727  0.6  0.730722  0.951887  0.424290  0.043578   
4  0.314286  0.155932  0.045455  0.6  0.856793  0.979326  0.753275  0.029817   

         X9       X10       X11       X12       X13     X14  Y  
0  0.956066  0.134645  0.000000  0.775162  0.706827  0.5625  2  
1  0.955782  0.129048  0.000495  0.777505  0.673568  0.9375  6  
2  0.957102  0.155044  0.004293  0.779986  0.741602  0.5625  3  
3  0.957102  0.155044  0.004293  0.779986  0.741602  0.5625  3  
4  0.956226  0.137795  0.001814  0.776052  0.734925  0.5625  4

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
train, test = train_test_split(df, test_size=0.30, random_state=99)

In [8]:

from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, classification_report #common metris to evaluate regression models


In [9]:

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 9)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


[[  1   0   0   0   0   1]
 [  0   1   1   1   1  12]
 [  0   0   3   1   0  14]
 [  2   2   0   3   0  26]
 [  0   2   5   0   1  26]
 [  0   1   7   5   6 178]]
              precision    recall  f1-score   support

           1       0.33      0.50      0.40         2
           2       0.17      0.06      0.09        16
           3       0.19      0.17      0.18        18
           4       0.30      0.09      0.14        33
           5       0.12      0.03      0.05        34
           6       0.69      0.90      0.78       197

    accuracy                           0.62       300
   macro avg       0.30      0.29      0.27       300
weighted avg       0.52      0.62      0.55       300



In [10]:
pd.DataFrame(model.predict(test[columns]), test['Y']).reset_index()

Y  0
0    6  6
1    4  6
2    3  6
3    5  3
4    6  6
..  .. ..
295  6  6
296  6  6
297  6  6
298  2  6
299  6  6

[300 rows x 2 columns]

In [11]:

from sklearn.dummy import DummyClassifier
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV


In [12]:
# Dummy classifier chooses an output prediction out of random within the range of the provided inputs
model = DummyClassifier()
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


[[  0   1   0   0   0   1]
 [  1   1   2   3   1   8]
 [  0   1   2   0   1  14]
 [  0   2   2   1   4  24]
 [  2   2   2   1   5  22]
 [  5  16  17  12  20 127]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.04      0.06      0.05        16
           3       0.08      0.11      0.09        18
           4       0.06      0.03      0.04        33
           5       0.16      0.15      0.15        34
           6       0.65      0.64      0.65       197

    accuracy                           0.45       300
   macro avg       0.17      0.17      0.16       300
weighted avg       0.46      0.45      0.45       300



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/dummy.py:131: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  warnings.warn("The default value of strategy will change from "


In [13]:
# Random forest classifier creates multiple decision trees to create an optimized classifier
model = RandomForestClassifier()
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))




[[  2   0   0   0   0   0]
 [  0   3   0   0   0  13]
 [  0   0   9   0   0   9]
 [  0   0   0   8   0  25]
 [  0   0   0   0  10  24]
 [  0   1   0   0   0 196]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         2
           2       0.75      0.19      0.30        16
           3       1.00      0.50      0.67        18
           4       1.00      0.24      0.39        33
           5       1.00      0.29      0.45        34
           6       0.73      0.99      0.84       197

    accuracy                           0.76       300
   macro avg       0.91      0.54      0.61       300
weighted avg       0.81      0.76      0.71       300



In [14]:
# Grid search cv: it's an exhaustive search to look for the best classifier based on the instructions provided 
parameters_f = [{'max_depth': range(3,8), 'n_estimators': range(5,10), 'max_features': range(4,11)}]
model = GridSearchCV(RandomForestClassifier(random_state=0), parameters_f)

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))



[[  1   0   0   0   0   1]
 [  0   0   0   0   0  16]
 [  0   0   3   1   0  14]
 [  0   0   2   2   0  29]
 [  0   0   0   0   4  30]
 [  0   0   0   0   1 196]]
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         2
           2       0.00      0.00      0.00        16
           3       0.60      0.17      0.26        18
           4       0.67      0.06      0.11        33
           5       0.80      0.12      0.21        34
           6       0.69      0.99      0.81       197

    accuracy                           0.69       300
   macro avg       0.63      0.31      0.34       300
weighted avg       0.66      0.69      0.59       300



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
# MLP classifier is a neural network that is created. It stands for multi layer perceptron
model = MLPClassifier()

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


[[  0   0   0   0   0   2]
 [  0   0   0   0   0  16]
 [  0   0   0   0   0  18]
 [  0   0   0   0   0  33]
 [  0   0   0   0   0  34]
 [  0   0   0   0   0 197]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        16
           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00        33
           5       0.00      0.00      0.00        34
           6       0.66      1.00      0.79       197

    accuracy                           0.66       300
   macro avg       0.11      0.17      0.13       300
weighted avg       0.43      0.66      0.52       300



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Grid search with Neural network. 
# sgd: stochastic gradient descent. algorithm for finding the minima and reducing the error
# alpha: L2 penalty
# activation: activation functions to pass through and create continuous, increasing, differentiable output (sometimes non linear)
# hidden layer size: set input and output layers are set based on the data. middle layers sizes can be changed as per requirement
parameters_n = [{'alpha': [0.0001, 0.001, 0.01, 0.1],'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'learning_rate': ['constant','adaptive'], 'hidden_layer_sizes':[(2,),(4,),(7,)]}]
model = GridSearchCV(MLPClassifier(random_state=2, max_iter = 500), parameters_n,cv=4)


model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't 

In [ ]:
from sklearn import svm

In [ ]:
model = svm.SVC()
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
model = GridSearchCV(model, params_grid, cv=5)


model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB, BernoulliNB, ComplementNB

In [ ]:
model = GaussianNB()

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=MultinomialNB(alpha=1.0, fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=BernoulliNB(alpha=1.5,  fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=ComplementNB(alpha=20, fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier, GradientBoostingClassifier ,VotingClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=2),
                         algorithm="SAMME",
                         n_estimators=200)
bdt.fit(train[columns], train['Y'])

pred = bdt.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
clf1 = GradientBoostingClassifier(n_estimators=100, learning_rate=1.17,
    max_depth=2, random_state=0)

clf1.fit(train[columns], train['Y'])

pred = clf1.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
eclfh = VotingClassifier(estimators=[('gbc', clf1), ('bdt', bdt)], voting='soft')
for clf, label in zip([clf1, bdt , eclfh], ['GBC',  'Ber naive Bayes', 'Ensemble']):
    scores = cross_val_score(clf, train[columns], train['Y'], cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))