In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('cleaned_dataset.csv')

In [3]:
df.head()

C1        X1        X2        X3  \
0       Building supplies and accessories  0.093398  0.014173  0.444444   
1         Industrial Supplies & Solutions  0.188406  0.055118  0.444444   
2  Computers,Mobile & related Accessories  0.281804  0.021260  0.555556   
3                Other Service Activities  0.217391  0.003937  0.444444   
4              Home, Furnishing and Decor  0.212560  0.005512  0.611111   

         X4        X5    C2        X6        X7        X8        X9       X10  \
0  0.657143  0.867384  ecom  0.870968  0.019481  0.833058  0.208023  0.000002   
1  0.657143  0.770609  ecom  0.563777  0.073593  0.833087  0.207978  0.000002   
2  0.657143  0.886499  ecom  0.810842  0.112554  0.832474  0.206731  0.001347   
3  0.314286  0.776583  ecom  0.741335  0.019481  0.832119  0.205823  0.001018   
4  0.314286  0.830346  ecom  0.813291  0.041126  0.832070  0.205714  0.000252   

        X11       X12   X13     score  Y  
0  0.323554  0.543076  0.90  1.473684  1  
1  0.323515  0.587864  0.80  1.294118  1  
2  0.322450  0.633580  0.70  1.400000  1  
3  0.321675  0.569124  0.55  1.250000  1  
4  0.321582  0.576634  0.55  1.416667  1

In [4]:
df = df.fillna(df.mean())

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8155 entries, 0 to 8154
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C1      8155 non-null   object 
 1   X1      8155 non-null   float64
 2   X2      8155 non-null   float64
 3   X3      8155 non-null   float64
 4   X4      8155 non-null   float64
 5   X5      8155 non-null   float64
 6   C2      8154 non-null   object 
 7   X6      8155 non-null   float64
 8   X7      8155 non-null   float64
 9   X8      8155 non-null   float64
 10  X9      8155 non-null   float64
 11  X10     8155 non-null   float64
 12  X11     8155 non-null   float64
 13  X12     8155 non-null   float64
 14  X13     8155 non-null   float64
 15  score   8155 non-null   float64
 16  Y       8155 non-null   int64  
dtypes: float64(14), int64(1), object(2)
memory usage: 1.1+ MB


In [6]:
columns = ['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13']

In [7]:
df[columns].head()

X1        X2        X3        X4        X5        X6        X7  \
0  0.093398  0.014173  0.444444  0.657143  0.867384  0.870968  0.019481   
1  0.188406  0.055118  0.444444  0.657143  0.770609  0.563777  0.073593   
2  0.281804  0.021260  0.555556  0.657143  0.886499  0.810842  0.112554   
3  0.217391  0.003937  0.444444  0.314286  0.776583  0.741335  0.019481   
4  0.212560  0.005512  0.611111  0.314286  0.830346  0.813291  0.041126   

         X8        X9       X10       X11       X12   X13  
0  0.833058  0.208023  0.000002  0.323554  0.543076  0.90  
1  0.833087  0.207978  0.000002  0.323515  0.587864  0.80  
2  0.832474  0.206731  0.001347  0.322450  0.633580  0.70  
3  0.832119  0.205823  0.001018  0.321675  0.569124  0.55  
4  0.832070  0.205714  0.000252  0.321582  0.576634  0.55

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
train, test = train_test_split(df, test_size=0.20, random_state=99)

In [10]:
(train.shape, test.shape)

((6524, 17), (1631, 17))

In [11]:

from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, classification_report #common metris to evaluate regression models


In [12]:

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 10)
model.fit(train[columns], round(train['Y']))

pred = model.predict(test[columns])
print(confusion_matrix(round(test['Y']), pred))
print(classification_report(round(test['Y']), pred))


[[ 28  19  25  28  22   8]
 [ 17 114  44  38  28  56]
 [ 27  76  92  30  48  45]
 [ 11  57  40  73  36  75]
 [ 27  59  35  40  88  31]
 [  4  44  39  53  12 162]]
              precision    recall  f1-score   support

           1       0.25      0.22      0.23       130
           2       0.31      0.38      0.34       297
           3       0.33      0.29      0.31       318
           4       0.28      0.25      0.26       292
           5       0.38      0.31      0.34       280
           6       0.43      0.52      0.47       314

    accuracy                           0.34      1631
   macro avg       0.33      0.33      0.33      1631
weighted avg       0.34      0.34      0.34      1631



In [13]:
pd.DataFrame(model.predict(test[columns]), test['Y']).reset_index()

Y  0
0     4  4
1     4  2
2     5  3
3     5  6
4     3  3
...  .. ..
1626  6  4
1627  2  4
1628  6  4
1629  5  3
1630  3  3

[1631 rows x 2 columns]

In [14]:

from sklearn.dummy import DummyClassifier
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV


In [15]:
# Dummy classifier chooses an output prediction out of random within the range of the provided inputs
model = DummyClassifier()
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


[[ 8 18 27 29 18 30]
 [24 59 59 62 46 47]
 [28 58 70 63 53 46]
 [21 46 45 61 58 61]
 [20 45 53 55 56 51]
 [19 51 53 60 64 67]]
              precision    recall  f1-score   support

           1       0.07      0.06      0.06       130
           2       0.21      0.20      0.21       297
           3       0.23      0.22      0.22       318
           4       0.18      0.21      0.20       292
           5       0.19      0.20      0.19       280
           6       0.22      0.21      0.22       314

    accuracy                           0.20      1631
   macro avg       0.18      0.18      0.18      1631
weighted avg       0.20      0.20      0.20      1631



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/dummy.py:131: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  warnings.warn("The default value of strategy will change from "


In [16]:
# Random forest classifier creates multiple decision trees to create an optimized classifier
model = RandomForestClassifier()
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))



#     1   2  3  4  5  6
# 1  [27  2  2  0  1  3] 
# 2  [ 6 21  4  1  1  2] 
# 3  [ 1  1 31  0  5 11] 
# 4  [ 3  2  4 25  5  6] 
# 5  [ 0  0  2  1 42 11] 
# 6  [ 0  0  3  0  5 62]  



[[ 79  17  11   5   9   9]
 [  1 199  16  17  19  45]
 [ 10  31 201  20  15  41]
 [  6  21  13 166  19  67]
 [  3  22   9  11 204  31]
 [  3   9  13  23   2 264]]
              precision    recall  f1-score   support

           1       0.77      0.61      0.68       130
           2       0.67      0.67      0.67       297
           3       0.76      0.63      0.69       318
           4       0.69      0.57      0.62       292
           5       0.76      0.73      0.74       280
           6       0.58      0.84      0.68       314

    accuracy                           0.68      1631
   macro avg       0.70      0.67      0.68      1631
weighted avg       0.70      0.68      0.68      1631



In [17]:
# Grid search cv: it's an exhaustive search to look for the best classifier based on the instructions provided 
parameters_f = [{'max_depth': range(3,8), 'n_estimators': range(5,10), 'max_features': range(4,11)}]
model = GridSearchCV(RandomForestClassifier(random_state=0), parameters_f)

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))



[[ 11  40  15  11  29  24]
 [  2 128  22  27  33  85]
 [  6  75  77  31  50  79]
 [  5  64  17  49  44 113]
 [  3  52  20  18 133  54]
 [  0  20  15  23   0 256]]
              precision    recall  f1-score   support

           1       0.41      0.08      0.14       130
           2       0.34      0.43      0.38       297
           3       0.46      0.24      0.32       318
           4       0.31      0.17      0.22       292
           5       0.46      0.47      0.47       280
           6       0.42      0.82      0.55       314

    accuracy                           0.40      1631
   macro avg       0.40      0.37      0.35      1631
weighted avg       0.40      0.40      0.37      1631



In [18]:
# MLP classifier is a neural network that is created. It stands for multi layer perceptron
model = MLPClassifier()

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


[[  4  35  14   4  49  24]
 [  0  87  53  14  39 104]
 [  1  76  46   8  84 103]
 [  1  40  25  23  63 140]
 [  1  37  25   8 148  61]
 [  1  16  15  12   2 268]]
              precision    recall  f1-score   support

           1       0.50      0.03      0.06       130
           2       0.30      0.29      0.30       297
           3       0.26      0.14      0.19       318
           4       0.33      0.08      0.13       292
           5       0.38      0.53      0.45       280
           6       0.38      0.85      0.53       314

    accuracy                           0.35      1631
   macro avg       0.36      0.32      0.27      1631
weighted avg       0.34      0.35      0.30      1631



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [19]:
# Grid search with Neural network. 
# sgd: stochastic gradient descent. algorithm for finding the minima and reducing the error
# alpha: L2 penalty
# activation: activation functions to pass through and create continuous, increasing, differentiable output (sometimes non linear)
# hidden layer size: set input and output layers are set based on the data. middle layers sizes can be changed as per requirement
parameters_n = [{'alpha': [0.0001, 0.001, 0.01, 0.1],'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'learning_rate': ['constant','adaptive'], 'hidden_layer_sizes':[(2,),(4,),(7,)]}]
model = GridSearchCV(MLPClassifier(random_state=2, max_iter = 500), parameters_n,cv=4)


model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't 

[[  1  35  11   1  56  26]
 [  0 125  31  10  42  89]
 [  0 109  26   4  88  91]
 [  1  73   9  14  66 129]
 [  0  53  15   3 150  59]
 [  0  46  10   6   0 252]]
              precision    recall  f1-score   support

           1       0.50      0.01      0.02       130
           2       0.28      0.42      0.34       297
           3       0.25      0.08      0.12       318
           4       0.37      0.05      0.08       292
           5       0.37      0.54      0.44       280
           6       0.39      0.80      0.53       314

    accuracy                           0.35      1631
   macro avg       0.36      0.32      0.25      1631
weighted avg       0.35      0.35      0.28      1631



/home/Srivamsi.s/anaconda3/envs/practice/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:568: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
from sklearn import svm

In [ ]:
model = svm.SVC()
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
model = GridSearchCV(model, params_grid, cv=5)


model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB, BernoulliNB, ComplementNB

In [ ]:
model = GaussianNB()

model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=MultinomialNB(alpha=1.0, fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=BernoulliNB(alpha=1.5,  fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
model=ComplementNB(alpha=20, fit_prior=True)
model.fit(train[columns], train['Y'])

pred = model.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier, GradientBoostingClassifier ,VotingClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=2),
                         algorithm="SAMME",
                         n_estimators=200)
bdt.fit(train[columns], train['Y'])

pred = bdt.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
clf1 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.05,
    max_depth=2, random_state=0)

clf1.fit(train[columns], train['Y'])

pred = clf1.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))


In [ ]:
# Random forest classifier creates multiple decision trees to create an optimized classifier
rf = RandomForestClassifier()
rf.fit(train[columns], train['Y'])

pred = rf.predict(test[columns])
print(confusion_matrix(test['Y'], pred))
print(classification_report(test['Y'], pred))




In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
eclfh = VotingClassifier(estimators=[('gbc', clf1), ('bdt', bdt), ('rf', rf)], voting='soft')
for clf, label in zip([clf1, bdt , rf, eclfh], ['GradientBoostingClassifier',  'AdaBoostClassifier', 'RandomForestClassifier', 'Ensemble']):
    scores = cross_val_score(clf, train[columns], train['Y'], cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))